feat:  add QNAP platform build (#828)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -441,6 +441,7 @@ jobs:
         env:
           VERSION: ${{ needs.get-release.outputs.version }}
         run: |
+          VERSION=${VERSION:-$(date +%y%m%d%H%M)} # Use current time as version if not specified
           cd ui/flutter
           flutter build web --web-renderer html
           cd ../../
@@ -468,6 +469,39 @@ jobs:
               || true
             done
           done
+          sudo apt update -y
+          sudo apt install -y pv python2 bsdmainutils
+          wget -O qdk2_0.32.bionic_amd64.deb "https://github.com/qnap-dev/qdk2/releases/download/v0.32/qdk2_0.32.bionic_amd64.deb"
+          dpkg -X qdk2_0.32.bionic_amd64.deb qdk2 # Direct installs will fail due to missing dependencies!
+          [[ -d qdk2 ]] || exit 1
+          export PATH=$(pwd)/qdk2/usr/bin:$(pwd)/qdk2/usr/share/qdk2/QDK/bin:${PATH}
+          wget -O Gopeed.template.tar.gz "https://github.com/GopeedLab/QpkgBuild/raw/refs/heads/master/template/Gopeed.template.tar.gz"
+          tar -zxf Gopeed.template.tar.gz
+          [[ -d Gopeed ]] || exit 1
+          goos=linux
+          goarch_arr=(amd64 arm64)
+          for goarch in "${goarch_arr[@]}"; do
+            qarch=x86_64
+            [[ "${goarch}" == "arm64" ]] && qarch=arm_64
+            name=gopeed-web-v${VERSION}-${goos}-${goarch}
+            cp dist/${name}/${name}/* Gopeed/${qarch}/
+          done
+          cd Gopeed
+          sed -i -e 's/__QPKG_VER__/${VERSION}/g' qpkg.cfg
+          qbuild || exit 1
+          for f in build/*; do echo ">>> build=[${f}]"; done
+          goos=qnap
+          goarch_arr=(amd64 arm64)
+          for goarch in "${goarch_arr[@]}"; do
+            qarch=x86_64
+            [[ "${goarch}" == "arm64" ]] && qarch=arm_64
+            sname=Gopeed_${VERSION}_${qarch}.qpkg
+            dname=gopeed-${goos}-v${VERSION}-${goarch}.qpkg
+            echo "sname=${sname}, dname=${dname}"
+            [[ -f build/${sname} ]] && cp -ra build/${sname} ../dist/zip/${dname}
+          done
+          for f in ../dist/zip/*; do echo ">>> dist=[${f}]"; done
+          cd ..
       - name: Upload
         uses: shogo82148/actions-upload-release-asset@v1
         with:
